- name: Copy auth and approve certs
  hosts: localhost
  become: true
  tasks:
    - name: Copy OCP Auth to for generic access
      copy:
        src: ../ocp22/auth
        dest: ../../ocp22
        force: yes
        mode: "u=rx,g=rwx,o=rwx"
