- name: qmCreateVM
  hosts: pve
  become: true
  vars_files:
    - 11-vars.yml
  tasks:
    - name: Stop VMs for OCP
      command: qm stop "{{ vimidStart }}{{ item.vimid }}"
      loop: "{{ vms_info }}"
    - name: Delete VMs for OCP
      command: qm destroy "{{ vimidStart }}{{ item.vimid }}"
      loop: "{{ vms_info }}"
