- name: Prep ignition files
  hosts: localhost
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Create change OCP project to default
      ansible.builtin.shell:
        cmd: "{{ item }}"
      with_items:
        - "oc create -f {{ playbook_dir }}/templates/nfs-rbac.yaml -n default"
        - "oc create -f {{ playbook_dir }}/templates/nfs-sc.yaml -n default"
        - "oc create -f {{ playbook_dir }}/templates/nfs-provisioner-deployment.yaml -n default"
